ram_birthday=input("Raj: what is your birthday Ram?")
print(ram_birthday)
sam_birthday=input("Raj: what is your birthday Sam?")
print(sam_birthday)
jodu_birthday=input("Raj: what is your birthday Jodu?")
print(jodu_birthday)
modhu_birthday=input("Raj: what is your birthday Modhu?")
print(modhu_birthday)
rito_birthday=input("Raj: what is your birthday Rito?")
print(rito_birthday)