import calender
import datetime 
print("1.January")
print("2.Febuary")
print("3.march")
print("4.April")
print("5.May")
print("6.June")
print("7.July")
print("8.August")
print("9.Semtember")
print("10.October")
print("11.November")
print("12.December")
now=datetime.datetime.now()
print("month and date is",now)